export type SeedMenuItem = {
  category: string
  name: string
  description: string
  imageUrl?: string | null
  prices: Record<string, number | null>
  sortOrder: number
}

export const menuSeedData: SeedMenuItem[] = [
  {
    category: 'Appetizers',
    name: 'Hormel Rib Tips',
    description: 'With Cookie\'s BBQ sauce.',
    prices: {},
    sortOrder: 21,
  },
  {
    category: 'Appetizers',
    name: 'Hot Wings',
    description: 'Plain, BBQ or buffalo on or on the side. Served with ranch or blue cheese.',
    imageUrl: '/images/food/appetizer-wings.jpg',
    prices: {},
    sortOrder: 22,
  },
  {
    category: 'Appetizers',
    name: 'Boneless Wings',
    description: 'Plain, BBQ or buffalo on or on the side. Served with ranch or blue cheese.',
    prices: {},
    sortOrder: 23,
  },
  {
    category: 'Appetizers',
    name: 'Jalapeno Poppers',
    description: '',
    prices: {},
    sortOrder: 24,
  },
  {
    category: 'Appetizers',
    name: 'Bread Stix',
    description: 'Served with marinara.',
    prices: {},
    sortOrder: 25,
  },
  {
    category: 'Appetizers',
    name: 'Cinnamon Stix',
    description: 'Approx. 5 stix.',
    prices: {},
    sortOrder: 26,
  },
  {
    category: 'Appetizers',
    name: 'Cheese Bread',
    description: 'Served with marinara.',
    imageUrl: '/images/food/appetizer-cheese-bread.jpg',
    prices: {},
    sortOrder: 27,
  },
  {
    category: 'Build Your Own Masterpiece',
    name: 'Build Your Own Masterpiece',
    description: 'Start with cheese included on our exclusive French bread dough pizza. Add your choice of toppings - each topping is an additional charge.',

    prices: {
      le_petit: 6.99,
      small: 8.99,
      medium: 10.99,
      large: 13.49,
      xl: 17.79,
      deep_dish_le_petit: 0.5,
      deep_dish_small: 0.75,
      deep_dish_medium: 1,
      deep_dish_large: 1,
      deep_dish_xl: 1,
      topping_le_petit: 0.99,
      topping_small: 1.49,
      topping_medium: 1.99,
      topping_large: 2.49,
      topping_xl: 2.75,
    },
    sortOrder: 1,
  },
  {
    category: 'Desserts',
    name: 'Apple Dessert',
    description: 'Sweet creamy spread, sliced apples, cinnamon sugar.',

    prices: { le_petit: 6.99, small: 8.99, medium: 10.99, large: 12.99 },
    sortOrder: 33,
  },
  {
    category: 'Desserts',
    name: 'Peach Dessert',
    description: 'Sweet creamy spread, sliced peaches, secret spices.',
    prices: { le_petit: 6.99, small: 8.99, medium: 10.99, large: 12.99 },
    sortOrder: 34,
  },
  {
    category: 'Desserts',
    name: 'Streusel Dessert',
    description: 'Sweet creamy spread, cinnamon streusel.',
    prices: { le_petit: 6.99, small: 8.99, medium: 10.99, large: 12.99 },
    sortOrder: 35,
  },
  {
    category: 'Desserts',
    name: 'Cherry Dessert',
    description: 'Sweet creamy spread, cherries, streusel.',
    prices: { le_petit: 6.99, small: 8.99, medium: 10.99, large: 12.99 },
    sortOrder: 36,
  },
  {
    category: 'Desserts',
    name: 'Blueberry Dessert',
    description: 'Sweet creamy spread, blueberries, streusel.',
    prices: { le_petit: 6.99, small: 8.99, medium: 10.99, large: 12.99 },
    sortOrder: 37,
  },
  {
    category: 'Desserts',
    name: 'Brownie Bites',
    description: '10 pieces.',
    prices: { single: 7.49 },
    sortOrder: 38,
  },
  {
    category: 'Exclusive Pizzas',
    name: 'Double Crust Pizza',
    description: 'Our unique double-crust pizza with two blankets of cheese, which turns into a tasty Italian meat pie!',
    prices: { small: 17.49, medium: 21.99, large: 25.99 },
    sortOrder: 14,
  },
  {
    category: 'Exclusive Pizzas',
    name: 'Triple Topper Pizza',
    description: 'Layers of dough and cheese seal in the flavor!',
    imageUrl: '/images/food/pizza-supreme.jpg',
    prices: { medium: 22.58, large: 25.99 },
    sortOrder: 15,
  },
  {
    category: 'Favorite Pizzas',
    name: 'Meatavore',
    description: 'Hearty enough to feed the Clear Lake lion within you!',

    prices: { le_petit: 9.99, small: 15.48, medium: 20.48, large: 25.25, xl: 29.24 },
    sortOrder: 6,
  },
  {
    category: 'Favorite Pizzas',
    name: 'Taco Pizza',
    description: 'Ole! A fiesta of flavor featuring Mexican style beef.',
    imageUrl: '/images/food/pizza-taco.jpg',
    prices: { le_petit: 8.99, small: 13.99, medium: 18.99, large: 22.99, xl: 26.99 },
    sortOrder: 7,
  },
  {
    category: 'Favorite Pizzas',
    name: 'Chicken Fiesta Pizza',
    description: 'A taco pizza with a chicken twist!',
    imageUrl: '/images/food/pizza-chicken.jpg',
    prices: { le_petit: 8.99, small: 13.99, medium: 18.99, large: 22.99, xl: 26.99 },
    sortOrder: 8,
  },
  {
    category: 'Favorite Pizzas',
    name: 'Quesadilla Pizza',
    description: 'Crispy, crunchy outside and melted cheese inside.',
    prices: { medium: 19.99, large: 22.99 },
    sortOrder: 9,
  },
  {
    category: 'Favorite Pizzas',
    name: 'Chicken Western Style Pizza',
    description: 'Feelin\' lucky? This pizza will make your day!',
    imageUrl: '/images/food/pizza-garlic-chicken.jpg',
    prices: { le_petit: 9.99, small: 15.48, medium: 20.48, large: 25.25, xl: 29.24 },
    sortOrder: 10,
  },
  {
    category: 'Favorite Pizzas',
    name: 'Chicken Vegetable Pizza',
    description: 'Fajita-style chicken surrounded by fresh vegetables.',
    prices: { le_petit: 8.99, small: 13.99, medium: 18.99, large: 22.99, xl: 26.99 },
    sortOrder: 11,
  },
  {
    category: 'Favorite Pizzas',
    name: 'Vegetarian Pizza',
    description: 'A garden full of delight.',
    imageUrl: '/images/food/pizza-vegetarian.jpg',
    prices: { le_petit: 8.99, small: 13.99, medium: 18.99, large: 22.99, xl: 26.99 },
    sortOrder: 12,
  },
  {
    category: 'Favorite Pizzas',
    name: 'Freek\'s Spicy Pizza',
    description: 'Inspired by Europe: spicy, bold and flavorful!',
    prices: { le_petit: 8.99, small: 13.99, medium: 18.99, large: 22.99, xl: 26.99 },
    sortOrder: 13,
  },
  {
    category: 'Gourmet Pizzas',
    name: 'Combo',
    description: 'The works! An exquisite combination of toppings.',

    prices: { le_petit: 8.99, small: 13.99, medium: 18.49, large: 22.76, xl: 26.49 },
    sortOrder: 2,
  },
  {
    category: 'Gourmet Pizzas',
    name: 'Super Combo',
    description: 'A more extravagant version of the combo.',
    imageUrl: '/images/food/pizza-combo-2.jpg',
    prices: { le_petit: 9.99, small: 15.48, medium: 20.48, large: 25.25, xl: 29.24 },
    sortOrder: 3,
  },
  {
    category: 'Gourmet Pizzas',
    name: 'BLT Pizza',
    description: 'A pizza that puts the sandwich to shame.',
    imageUrl: '/images/food/pizza-blt.jpg',
    prices: { le_petit: 9.99, small: 15.48, medium: 20.48, large: 25.25, xl: 29.24 },
    sortOrder: 4,
  },
  {
    category: 'Gourmet Pizzas',
    name: 'Shrimp Pizza',
    description: 'Arrrr matey! A seafarer\'s favorite!',
    prices: { le_petit: 9.99, small: 15.48, medium: 20.48, large: 25.25, xl: 29.24 },
    sortOrder: 5,
  },
  {
    category: 'Oven-Baked Pastas',
    name: 'Lasagna',
    description: 'Lasagna with tomato/meat sauce, Italian sausage.',

    prices: { single: 9.99 },
    sortOrder: 16,
  },
  {
    category: 'Oven-Baked Pastas',
    name: 'Meat Ravioli',
    description: 'Meat ravioli with tomato/meat sauce or creamy Alfredo sauce.',

    prices: { single: 9.99 },
    sortOrder: 17,
  },
  {
    category: 'Oven-Baked Pastas',
    name: 'Tortellini',
    description: 'Meat or cheese tortellini with tomato/meat sauce or creamy Alfredo sauce.',

    prices: { single: 9.99 },
    sortOrder: 18,
  },
  {
    category: 'Oven-Baked Pastas',
    name: 'Spaghetti',
    description: 'Spaghetti with tomato/meat sauce, beef, cheese.',
    prices: { single: 8.99 },
    sortOrder: 19,
  },
  {
    category: 'Oven-Baked Pastas',
    name: 'Super Spaghetti',
    description: 'Spaghetti with tomato/meat sauce, peppers, mushrooms, onions, pepperoni, beef, cheese.',
    prices: { single: 9.99 },
    sortOrder: 20,
  },
  {
    category: 'Salads',
    name: 'Chef Salad',
    description: 'All salads are served with your choice of dressing!',

    prices: { single: 7.49 },
    sortOrder: 28,
  },
  {
    category: 'Salads',
    name: 'Taco Salad',
    description: '',
    prices: { single: 7.49 },
    sortOrder: 29,
  },
  {
    category: 'Salads',
    name: 'Chicken Chef Salad',
    description: '',
    prices: { single: 7.49 },
    sortOrder: 30,
  },
  {
    category: 'Salads',
    name: 'Shrimp Salad',
    description: '',
    prices: { single: 7.49 },
    sortOrder: 31,
  },
  {
    category: 'Salads',
    name: 'Side Salad',
    description: '',
    prices: { single: 4.29 },
    sortOrder: 32,
  },
]
